---
title: "Electricity vs. Natural Gas"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## Load packages

```{r}

library(tidyverse)
library(gghighlight)
library(showtext)

##Add typeface "Inter" from Google Fonts
font_add_google(name = "Montserrat", family = "inter")
##Add typeface "Barlow" from Google Fonts
font_add_google(name = "Barlow", family="barlow")

## enable use of Google Fonts
showtext_auto()

```

Read in data

```{r}

northeast_midwest <-  readxl::read_xlsx(here::here("data/fuel_uses/northeast_midwest.xlsx"), skip=4) %>%
  janitor::clean_names() %>% 
  drop_na()

colnames(northeast_midwest)[1] = "fuel"

northeast_midwest <- northeast_midwest[c(1,3), ] 

#str(northeast_midwest)

northeast_midwest[5:8] <- lapply(northeast_midwest[5:8], as.numeric)


ne_mw_clean <-  pivot_longer(northeast_midwest, cols = -fuel, names_to = "region", values_to = "n_homes") %>% 
    pivot_wider(names_from = fuel, values_from = n_homes) %>% 
  janitor::clean_names() %>% 
  mutate(pct = natural_gas/all_homes)


south_west <- readxl::read_xlsx(here::here("data/fuel_uses/south_west.xlsx"), skip= 7) %>% 
  janitor::clean_names() %>% 
  drop_na()  

colnames(south_west)[1] = "fuel"
colnames(south_west)[5] = "east_south_central"
colnames(south_west)[6] = "west_south_central"

south_west <- south_west[c(1,3), ] 

south_west[2:ncol(south_west)] <- lapply(south_west[2:ncol(south_west)], as.numeric)

sw_clean <- pivot_longer(south_west, cols = -fuel, names_to = "region", values_to = "n_homes") %>% 
    pivot_wider(names_from = fuel, values_from = n_homes) %>% 
  janitor::clean_names() %>% 
  mutate(pct = natural_gas/all_homes)

all_reg_clean <- rbind(sw_clean, ne_mw_clean)

spec_reg_only <- all_reg_clean[c(2,6,12,15), ] 

region_polished <- c("South","West","Northeast","Midwest")

spec_reg_only$region_polished <- region_polished


nat <- all_reg_clean %>% 
  filter(region == "total_u_s_a")

national_average <- nat$pct[1]



```

```{r}

xmin_start = 0.55
xmax_start = 1.45

xmin_top = 0.8
xmax_top = 1.2

ymax_top = 1.03

ymin_tot = -0.01
ymax_tot = 1

alpha_tot = 0.35

bat_fill = "gray"
bat_outline = "black"

spec_reg_only <- spec_reg_only %>%
  arrange(rev(desc(pct))) %>%
  mutate(region = factor(region, levels = unique(region)))

energy_bars <- ggplot(data = spec_reg_only, aes(x = reorder(region_polished, pct), y = pct)) +
  #first
  geom_rect(
    xmin = xmin_start, xmax = xmax_start, ymin = ymin_tot,ymax = ymax_tot,
    alpha = alpha_tot,fill = bat_fill,col = bat_outline)+
  ##second
  geom_rect(
    xmin = xmin_start+1, xmax = xmax_start+1, ymin = ymin_tot,ymax = ymax_tot,
    alpha = alpha_tot,fill = bat_fill,col = bat_outline)+
  ##third
   geom_rect(
    xmin = xmin_start+2, xmax = xmax_start+2, ymin = ymin_tot,ymax = ymax_tot,
    alpha = alpha_tot,fill = bat_fill,col = bat_outline)+
  ##fourth
   geom_rect(
    xmin = xmin_start+3, xmax = xmax_start+3, ymin = ymin_tot,ymax = ymax_tot,
    alpha = alpha_tot,fill = bat_fill,col = bat_outline)+
  # ##fifth
  # geom_rect(
  #   xmin = xmin_start+4, xmax = xmax_start+4, ymin = ymin_tot,ymax = ymax_tot,
  #   alpha = alpha_tot,fill = "white",col = "white")+
  # #six
  #  geom_rect(
  #   xmin = xmin_start+5, xmax = xmax_start+5, ymin = ymin_tot,ymax = ymax_tot,
  #   alpha = alpha_tot,fill = bat_fill,col = bat_outline)+
  # ##7
  #  geom_rect(
  #   xmin = xmin_start+6, xmax = xmax_start+6, ymin = ymin_tot,ymax = ymax_tot,
  #   alpha = alpha_tot,fill = bat_fill,col = bat_outline)+
  # ##8
  #  geom_rect(
  #   xmin = xmin_start+7, xmax = xmax_start+7, ymin = ymin_tot,ymax = ymax_tot,
  #   alpha = alpha_tot,fill = bat_fill,col = bat_outline)+
  # ##9
  #  geom_rect(
  #   xmin = xmin_start+8, xmax = xmax_start+8, ymin = ymin_tot,ymax = ymax_tot,
  #   alpha = alpha_tot,fill = bat_fill,col = bat_outline)+
  
  geom_rect(xmin=xmin_top, xmax =xmax_top, ymin=1, ymax=ymax_top)+
   geom_rect(xmin=xmin_top+1, xmax =xmax_top+1, ymin=1, ymax=ymax_top)+
   geom_rect(xmin=xmin_top+2, xmax =xmax_top+2, ymin=1, ymax=ymax_top)+
   geom_rect(xmin=xmin_top+3, xmax =xmax_top+3, ymin=1, ymax=ymax_top)+
   # geom_rect(xmin=xmin_top+4, xmax =xmax_top+4, ymin=1, ymax=ymax_top)+
   # geom_rect(xmin=xmin_top+5, xmax =xmax_top+5, ymin=1, ymax=ymax_top)+
   # geom_rect(xmin=xmin_top+6, xmax =xmax_top+6, ymin=1, ymax=ymax_top)+
   # geom_rect(xmin=xmin_top+7, xmax =xmax_top+7, ymin=1, ymax=ymax_top)+
   #  geom_rect(xmin=xmin_top+8, xmax =xmax_top+8, ymin=1, ymax=ymax_top)+

    geom_col(fill="green3", width = 0.75) +
    labs(title = "Percent of Homes Powered by Natural Gas",
         subtitle= "Percent of homes in each general region that supplement electricity usage \n with natural gas, compared to the national average") +
 geom_hline(yintercept=national_average)+
  geom_text(aes(label=scales::percent(pct, accuracy = 1)),
            y=0.88,
            size = 10, 
            color="black")+
  ylim(0,1.2)+
  
   annotate(geom="text", x=5 ,
            y=national_average-0.3, 
           label="National Average",
           size =8,
              color="transparent")+
   annotate(geom="text", x=4.7 ,
            y=national_average-0.35, 
           label="National Average",
           size =12,
              color="black")+
  geom_segment(aes(x = 4.4, y = national_average-0.2, xend = 4.2, yend = national_average), 
                 arrow = arrow(type = "closed", length = unit(0.05, "inches")),
                 color = "black")+
  theme_minimal() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(
          hjust=0.5,
          family = "inter",
          face="bold",
          size=25
          ),
          plot.title = element_text(
              face="bold",
               family = "inter",
                size = 40,
                 hjust = 0.5),
          plot.subtitle = element_text(
               family = "inter",
                size = 30,
                 hjust = 0.5,
               lineheight = 0.5,
               margin = margin(b = 10, unit = "pt")
               ),
      # margin=margin(1,1,1,1, unit="cm"),
      plot.background = element_rect(fill = "transparent", color = "transparent"), # make plot background transparent
        panel.background = element_rect(fill = "transparent", color ="transparent"),
      
        )+
    
  coord_flip()

energy_bars

ggsave(here::here("images/energybars.png"), plot = energy_bars, width = 6, height = 4, dpi = 300)
```

```{r}


color_pacific = "springgreen4"
color_mountain = "#93C572"
color_wnc = "#FAC898"
color_enc = "#FFA500"
color_ne = '#D22B2B'
color_ma = "#FAA0A0"
color_sa = "#0F52BA"
color_esc = "#6495ED"
color_wsc ="#87CEEB"

##create a color palette for each of the specific census regions
region_palette <- c("Pacific" = color_pacific, "Mountain" = color_mountain, "West North Central" = color_wnc, "East North Central" = color_enc, "New England" = color_ne, "Middle Atlantic" = color_ma, "South Atlantic" = color_sa, "East South Central" = color_esc, "West South Central" = color_wsc)
```
